### ISSUE TITLE
Item ID

### ISSUE THREAD

**Issue by Gurenji** [LilacTree/partner-gifter#1]
Hello there,

I'm having some trouble with finding the item ID for common pet food.
Trying to get te mod to feed it to my pet but when I enter the command to find the ID nothing shows up.

![image](https://user-images.githubusercontent.com/49957981/61127101-93a77200-a4ae-11e9-9b28-6e7956b6ffda.png)

Anything I am doing wrong? will be happy to provide any data you might need to see what I am doing wrong or perhaps it needs a fix.

Thank you in advance!

**Comment by LilacTree** [comment]
Unfortunately, this module only works for partners and not regular pets.
